import { describe, expect, it, vi } from "vitest";
import { createGitHubPullRequestClient } from "./client.ts";

const TOKEN = "github-secret+/=";
const LOOKUP = {
  repository: {
    owner: "ferueda",
    repository: "harness",
    httpsRemote: "https://github.com/ferueda/harness.git",
  },
  baseBranch: "main",
  headBranch: "codex/FER-286",
} as const;

describe("GitHub pull request client", () => {
  it("uses exact lookup filters and validates returned pull requests", async () => {
    const fetchRequest = vi.fn<typeof fetch>(async () =>
      jsonResponse([pullRequestResponse({ state: "closed", mergedAt: "2026-07-23T00:00:00Z" })]),
    );
    const client = createGitHubPullRequestClient({ token: TOKEN, fetch: fetchRequest });

    await expect(client.listPullRequests(LOOKUP)).resolves.toEqual([
      {
        url: "https://github.com/ferueda/harness/pull/286",
        number: 286,
        state: "closed",
        merged: true,
        owner: "ferueda",
        repository: "harness",
        baseBranch: "main",
        headOwner: "ferueda",
        headRepository: "harness",
        headBranch: "codex/FER-286",
        headSha: "a".repeat(40),
      },
    ]);

    const [url, options] = fetchRequest.mock.calls[0] ?? [];
    expect(String(url)).toContain("state=all");
    expect(String(url)).toContain("head=ferueda%3Acodex%2FFER-286");
    expect(String(url)).toContain("base=main");
    const headers = new Headers(options?.headers);
    expect(headers.get("authorization")).toBe(`Bearer ${TOKEN}`);
    expect(headers.get("x-github-api-version")).toBe("2026-03-10");
  });

  it("sends the minimal create payload", async () => {
    const fetchRequest = vi.fn<typeof fetch>(async () => jsonResponse(pullRequestResponse()));
    const client = createGitHubPullRequestClient({ token: TOKEN, fetch: fetchRequest });

    await client.createPullRequest({
      ...LOOKUP,
      title: "Add FER-286 spec",
      body: "Generated by Harness",
    });

    const [, options] = fetchRequest.mock.calls[0] ?? [];
    expect(options?.method).toBe("POST");
    expect(JSON.parse(String(options?.body))).toEqual({
      title: "Add FER-286 spec",
      body: "Generated by Harness",
      head: "codex/FER-286",
      base: "main",
    });
  });

  it("rejects malformed responses", async () => {
    const client = createGitHubPullRequestClient({
      token: TOKEN,
      fetch: async () => jsonResponse([{ number: "not-a-number" }]),
    });

    await expect(client.listPullRequests(LOOKUP)).rejects.toMatchObject({
      code: "invalid-response",
    });
  });

  it("redacts raw and encoded credentials from request failures", async () => {
    const encoded = encodeURIComponent(TOKEN);
    const client = createGitHubPullRequestClient({
      token: TOKEN,
      fetch: async () => {
        throw new Error(`failed ${TOKEN} ${encoded}`);
      },
    });

    const error = await client.listPullRequests(LOOKUP).catch((caught: unknown) => caught);
    expect(error).toMatchObject({ code: "github-failed" });
    expect(String(error)).not.toContain(TOKEN);
    expect(String(error)).not.toContain(encoded);
    expect(String(error)).toContain("[REDACTED]");
  });

  it("normalizes and redacts response body failures", async () => {
    const client = createGitHubPullRequestClient({
      token: TOKEN,
      fetch: async () =>
        new Response(
          new ReadableStream({
            pull(controller) {
              controller.error(new Error(`stream failed ${TOKEN}`));
            },
          }),
        ),
    });

    const error = await client.listPullRequests(LOOKUP).catch((caught: unknown) => caught);
    expect(error).toMatchObject({ code: "github-failed" });
    expect(String(error)).not.toContain(TOKEN);
    expect(String(error)).toContain("[REDACTED]");
  });
});

function pullRequestResponse(
  overrides: { state?: "open" | "closed"; mergedAt?: string | null } = {},
) {
  return {
    html_url: "https://github.com/ferueda/harness/pull/286",
    number: 286,
    state: overrides.state ?? "open",
    merged_at: overrides.mergedAt ?? null,
    base: {
      ref: "main",
      repo: { name: "harness", owner: { login: "ferueda" } },
    },
    head: {
      ref: "codex/FER-286",
      sha: "a".repeat(40),
      repo: { name: "harness", owner: { login: "ferueda" } },
    },
  };
}

function jsonResponse(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "content-type": "application/json" },
  });
}
